### ISSUE TITLE
[BUG] tezos-setup fails when re-creating an existing node

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#642]
# Description

`tezos-setup` fails when re-creating an existing node

# To Reproduce

- run `tezos-setup` and set up baking or just node
- run `tezos-setup` againg to redo the node
- observe setup fails to clear out existing directory, exits with error:

```
Would you like your setup to automatically start on boot?
1. yes (default)               Enable the services, running them both now and on every boot
2. no                          Start the services this time only
>
Trying to bootstrap octez-node
The Tezos node data directory already has some blockchain data:
- /mnt/extreme_ssd/tezos/node-mainnet/context
- /mnt/extreme_ssd/tezos/node-mainnet/identity.json
- /mnt/extreme_ssd/tezos/node-mainnet/peers.json
- /mnt/extreme_ssd/tezos/node-mainnet/store
- /mnt/extreme_ssd/tezos/node-mainnet/lock
Delete this data and bootstrap the node again? <y/N> y

Node directory cleaned.
Which history mode do you want your node to run in?
1. rolling (default)           Store a minimal rolling window of chain data, lightest
                               option
2. full                        Store enough chain data to reconstruct the complete chain
                               state
3. archive                     Store all the chain data, very storage-demanding
>
Apr 17 12:16:58.366 - node.config.validation: the node configuration has been successfully validated.
The Tezos node can take a significant time to bootstrap from scratch.
Bootstrapping from a snapshot is suggested instead.
How would you like to proceed?
1. download rolling (default)  Import rolling snapshot from xtz-shots.io (recommended)
2. file                        Import snapshot from a file
3. url                         Import snapshot from a url
4. skip                        Skip snapshot import and synchronize with the network from
                               scratch
>
Downloading the snapshot from https://mainnet-v16.xtz-shots.io/mainnet-3373717.rolling
Progress: 100 %, 5965 MB
octez-node: Error:
              Invalid data directory '/mnt/extreme_ssd/tezos/node-mainnet': Please provide a clean directory by removing the following files: context.

Error in Tezos Setup Wizard, exiting.
The error has been logged to /home/pi/tezos_setup.log
pi@raspberrypi:~ $ cat /home/pi/tezos_setup.log
Command '['sudo', '-u', 'tezos', 'octez-node-mainnet', 'config', 'update', '--history-mode', 'rolling']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tezos_baking/tezos_setup_wizard.py", line 558, in main
    setup.run_setup()
  File "/usr/lib/python3/dist-packages/tezos_baking/tezos_setup_wizard.py", line 502, in run_setup
    self.bootstrap_node()
  File "/usr/lib/python3/dist-packages/tezos_baking/tezos_setup_wizard.py", line 390, in bootstrap_node
    self.import_snapshot()
  File "/usr/lib/python3/dist-packages/tezos_baking/tezos_setup_wizard.py", line 369, in import_snapshot
    proc_call(
  File "/usr/lib/python3/dist-packages/tezos_baking/wizard_structure.py", line 184, in proc_call
    return subprocess.check_call(shlex.split(cmd))
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '-u', 'tezos', 'octez-node-mainnet', 'snapshot', 'import', '/tmp/octez_node.snapshot', '--block', 'BLvbcpG7RgsUqFbpMtX2uh44s7YuW7gPtvaT69N1sMXUTsKmxVh']' returned non-zero exit status 124.
```

# Expected behavior

old data directory is cleared out, new node is created from snapshot without 

# Environment

- OS: Debian Buster on RaspberryPi

```
$ dpkg -s tezos-baking
Package: tezos-baking
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 119
Maintainer: Serokell <hi@serokell.io>
Architecture: arm64
Version: 2:16.1-0ubuntu1~focal
Depends: tezos-baker-ptlimapt, tezos-baker-ptmumbai, tezos-node, acl, python3:any
Conffiles:
 /etc/default/tezos-baking-custom@ 81baabdb5c0c2ff7a501524eaddd8fc7
 /etc/default/tezos-baking-ghostnet 7e5582296e0ec67cc4058ee2521e3d60
 /etc/default/tezos-baking-limanet 7e5582296e0ec67cc4058ee2521e3d60
 /etc/default/tezos-baking-mainnet 7e5582296e0ec67cc4058ee2521e3d60
 /etc/default/tezos-baking-mumbainet 7e5582296e0ec67cc4058ee2521e3d60
 /etc/default/tezos-baking-hangzhounet 08abe74f9e52913911d171332f36d91b obsolete
 /etc/default/tezos-baking-florencenet 08abe74f9e52913911d171332f36d91b obsolete
 /etc/default/tezos-baking-granadanet 08abe74f9e52913911d171332f36d91b obsolete
 /etc/default/tezos-baking-ithacanet b2baace90b8c5837d8c49572b8486fcc obsolete
 /etc/default/tezos-baking-jakartanet b2baace90b8c5837d8c49572b8486fcc obsolete
 /etc/default/tezos-baking-kathmandunet 7e5582296e0ec67cc4058ee2521e3d60 obsolete
Description: Package that provides systemd services that orchestrate other services from Tezos packages
Homepage: https://gitlab.com/tezos/tezos/
```

**Comment by itkach** [comment]
running `tezos-setup` again after this failure I get this:

```
Trying to bootstrap octez-node
The Tezos node data directory already has some blockchain data:
- /mnt/extreme_ssd/tezos/node-mainnet/peers.json
- /mnt/extreme_ssd/tezos/node-mainnet/context
Delete this data and bootstrap the node again? <y/N> y

Node directory cleaned.
```

**Comment by itkach** [comment]
running tezos-setup for the third time, now there's no previous data and the wizard goes through without the error

**Comment by itkach** [comment]
When I started tezos-setup the first time the node was actually running (I think), so maybe some files were re-created after cleanup thought it was done.
